steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'alpha'
      - 'storage'
      - 'cp'
      - 'index.html'
      - 'gs://my-static-website-bucket-12345/index.html'
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '600s'